# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [92]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [93]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

chipo = pd.read_csv(url, sep= "\t")

chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [96]:
# chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x.strip('$')))
product_more_than_10 = chipo[chipo['item_price'] > 10]['item_name'].unique()
product_more_than_10.shape[0]

31

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [98]:
item = pd.DataFrame(data=chipo, columns=['item_name', 'choice_description', 'product_price'])
item

,item_name,choice_description,product_price
0,Chips and Fresh Tomato Salsa,NaN,NaN
1,Izze,[Clementine],NaN
2,Nantucket Nectar,[Apple],NaN
3,Chips and Tomatillo-Green Chili Salsa,NaN,NaN
4,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",NaN
...,...,...,...
4617,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",NaN
4618,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",NaN
4619,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",NaN
4620,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",NaN
4621,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",NaN

### Step 6. Sort by the name of the item

In [25]:
item.sort_values('item_name', inplace=True)
item

,item_name,choice_description,item_price
3389,6 Pack Soft Drink,[Diet Coke],12.98
341,6 Pack Soft Drink,[Diet Coke],6.49
1849,6 Pack Soft Drink,[Coke],6.49
1860,6 Pack Soft Drink,[Diet Coke],6.49
2713,6 Pack Soft Drink,[Coke],6.49
...,...,...,...
2384,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [76]:
q = item.sort_values('item_price', ascending=False).head(1)
# q['item_name'].values[0]
most_expensive_ordered = item[item['item_name'] == q['item_name'].values[0]]
most_expensive_ordered.groupby('item_name').count()

                              choice_description  item_price
item_name
Chips and Fresh Tomato Salsa                   0         110

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [53]:
ordered = chipo[chipo['item_name'] == 'Veggie Salad Bowl'].count()
int(ordered['quantity'])

18

In [56]:
ordered_2 = chipo.groupby('item_name')['item_name'].count()
ordered_2 = ordered_2[ordered_2.index == 'Veggie Salad Bowl']
ordered_2

item_name
Veggie Salad Bowl    18
Name: item_name, dtype: int64

### Step 9. How many times did someone order more than one Canned Soda?

In [89]:
c = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)].groupby('item_name')['item_name'].count()
c

item_name
Canned Soda    20
Name: item_name, dtype: int64